apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypythonapp
spec:
  selector:
    matchLabels:
      app: mypythonapp
  template:
    metadata:
      labels:
        app: mypythonapp
    spec:
      containers:
      - name: mypythonapp
        image: https://hub.docker.com/repository/docker/budde9666/flask-hello/tags/2.0/sha256-e77e71e1eac26fe79d9c6f8754ffa3f77e31c9848b1fb006140b5199f2c87380
        ports:
        - containerPort: 5000
