apiVersion: v1
kind: Service
metadata:
  name: mypythonapp
  labels:
    app: mypythonapp
spec:
  selector:
    app: mypythonapp
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
