apiVersion: v1
kind: Service
metadata:
  name: pythonapp
  labels:
    app: pythonapp
spec:
  selector:
    app: pythonapp
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
